### ISSUE TITLE
Replace isAuthenticated and isLoading Properties in MenuBar and MakeChange Pages

### ISSUE THREAD

**Issue by BriDavidson** [FusionAuth/fusionauth-quickstart-javascript-react-web#26]
**Description**
We are currently using the old `isAuthenticated` and isLoading Properties within the Menu Bar and Make Change pages. This will need to be swapped out to use `isLoggedIn` and `isFetchingUserInfo`. 

Currently, due to these old states being left behind, the Menu bar and Make Change page are not functioning or appearing as expected.

**Steps to Reproduce**

1. Log In as a valid Registered Change Bank user
2. Click on the Make Change link in the menu bar

**Current Behavior**
User is unable to view the Make Change page and the menu bar focus state does not change

**Expected Behavior**
User should be able to see which navlink they are viewing as displayed by a focus state and the make change page should display

**Comment by JakeLo123** [comment]
closing - https://github.com/FusionAuth/fusionauth-quickstart-javascript-react-web/pull/27
