### ISSUE TITLE
404 Error on Request Being Made to Get --logo-url in Kickstart styles.css

### ISSUE THREAD

**Issue by BriDavidson** [FusionAuth/fusionauth-quickstart-javascript-react-web#4]
**Description**
When attempting to pull in the `--logo-url `from the kickstart styles.css file, a `404` error is encountered this is notable within the console and network logging when viewing the Login page. It seems that the URL specified for `--logo-url` needs to be validated and updated or we may consider different handling if the logo is not required to show on this view.

**Steps to Reproduce**

Open the [styles.css](https://github.com/FusionAuth/fusionauth-quickstart-javascript-react-web/blob/main/kickstart/css/styles.css) file.
Locate the `--logo-url` property in the `:root` section.
Attempt to access the URL specified for `--logo-url`.

**Expected Result**
The URL specified for `--logo-url` should be valid, and the logo image should be successfully loaded.

**Actual Result**
Encountering a 404 error when trying to access the URL specified for `--logo-url`.

**Supporting Test Artifacts**
https://jam.dev/c/6b826daf-786c-4257-862e-5f193e30cae7 

**Recommendation**

Validate the URL provided for `--logo-url` to ensure its correctness.
If the URL is incorrect or leads to a non-existent resource, update it with the correct and accessible URL for the logo image.
If the logo is not required to display in this view we should consider removing reference to the logo on this page

Please let me know if further information or clarification is needed.

**Comment by JakeLo123** [comment]
[This PR](https://github.com/FusionAuth/fusionauth-quickstart-javascript-react-web/pull/11) will probably fix this!

**Comment by BriDavidson** [comment]
This has been resolved
